### ISSUE TITLE
Release new version now that SoftwareSerial is no longer a dependency

### ISSUE THREAD

**Issue by CosminPerRam** [nthnn/microlzw#1]
Hey, thanks for this library.
I had problems whilst trying to install it from the Arduino IDE because of the SoftwareSerial dependency, now that it has been removed, can we get a new release?

**Comment by nthnn** [comment]
Well, I did not expect someone else other than myself would use this library. Maybe next day after tomorrow I'll work on a new version with some improvements. Not sure tho.

**Comment by nthnn** [comment]
And oh... this doesn't require the SoftwareSerial library.

**Comment by nthnn** [comment]
Made a new release, although the Arduino library registry might take hours to update.
